[package]
name = "shigure"
version = "0.1.0"
edition = "2024"

[dependencies]
tao="0.34.0"
wry="0.52.0"
rainmeter={path = "../rainmeter"}
windows = "0.61.3"
once_cell = "1.19.0"

# This is a rainmeter module
[lib]
crate-type = ["cdylib"]
