[package]
name = "mado_doc"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
mado = { path = "../mado" }
wry_cmd = { path = "../../wry_cmd/wry_cmd", features = ["docs"] }
schemars = "1.0.4"
serde_json = "1.0.141"
